import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-red-500">Hello World</h1>
      </main>
      <footer className="fixed bottom-0 w-full">
        <div className="items-center grid-flow-col">
            <p className="text-center text-sm text-gray-500"> Made by <a href="GitHub.com/MadeOfBees" className="text-blue-500">MadeOfBees</a> on Github </p>
        </div>
      </footer>
    </>
  );
}
