import Head from "next/head";
import Footer from "@/Components/footer";
import Navbar from "@/Components/navbar";

export default function Home() {
  const userID = 1;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userID={userID} />
      <main>
        <h1 className="text-6xl font-bold">Welcome to ShelterGame</h1>
        <p className="text-xl">Get started by signing in</p>
      </main>
      <Footer />
    </>
  );
}
